<?php

/**
 * @file
 * Contains mystics_services.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mystics_services_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mystics_services module.
    case 'help.page.mystics_services':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides a services list for Mystics by Gerald Janosko.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function mystics_services_theme() {
  return [
    'services_list' => [
      'variables' => [
        'content' => NULL
      ],
      'render element' => 'children',
    ],
  ];
}
