<?php

/**
 * @file
 * Contains mystics_store.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mystics_store_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mystics_store module.
    case 'help.page.mystics_store':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides a store management interface for Mystics Stripe by Gerald Janosko.') . '</p>';
      return $output;

    default:
  }
}
