<?php

/**
 * @file
 * Contains mystics_page_headers.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mystics_page_headers_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mystics_page_headers module.
    case 'help.page.mystics_page_headers':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides page headers for each page using media objects.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function mystics_page_headers_theme() {
  return [
    'mphblock' => [
      'variables' => [
        'content' => NULL
      ],
      'render element' => 'children',
    ],
  ];
}
